version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "electron"
        update-types: ["version-update:semver-major"]
      - dependency-name: "electron-builder"
        update-types: ["version-update:semver-major"]
    groups:
      npm-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      actions:
        patterns:
          - "*"
